# coding: utf-8

"""
    Rotten Tomatoes

    Test our API services using I/O Docs.

    The version of the OpenAPI document: 1.0
    Contact: mike.ralphson@gmail.com
    Created by: https://github.com/mermade/mashery2openapi
"""

from rotten_tomatoes_python_sdk.paths.lists_dvds_current_releases_json.get import GetCurrentReleasesRaw
from rotten_tomatoes_python_sdk.paths.lists_dvds_new_releases_json.get import GetNewReleasesJsonRaw
from rotten_tomatoes_python_sdk.paths.lists_dvds_top_rentals_json.get import GetTopRentalsJsonRaw
from rotten_tomatoes_python_sdk.paths.lists_dvds_upcoming_json.get import GetUpcomingDvdsRaw


class DVDListsApiRaw(
    GetCurrentReleasesRaw,
    GetNewReleasesJsonRaw,
    GetTopRentalsJsonRaw,
    GetUpcomingDvdsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
