# coding: utf-8

"""
    Rotten Tomatoes

    Test our API services using I/O Docs.

    The version of the OpenAPI document: 1.0
    Contact: mike.ralphson@gmail.com
    Created by: https://github.com/mermade/mashery2openapi
"""

from rotten_tomatoes_python_sdk.paths.lists_dvds_current_releases_json.get import GetCurrentReleases
from rotten_tomatoes_python_sdk.paths.lists_dvds_new_releases_json.get import GetNewReleasesJson
from rotten_tomatoes_python_sdk.paths.lists_dvds_top_rentals_json.get import GetTopRentalsJson
from rotten_tomatoes_python_sdk.paths.lists_dvds_upcoming_json.get import GetUpcomingDvds
from rotten_tomatoes_python_sdk.apis.tags.dvd_lists_api_raw import DVDListsApiRaw


class DVDListsApi(
    GetCurrentReleases,
    GetNewReleasesJson,
    GetTopRentalsJson,
    GetUpcomingDvds,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: DVDListsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = DVDListsApiRaw(api_client)
