# coding: utf-8

"""
    Rotten Tomatoes

    Test our API services using I/O Docs.

    The version of the OpenAPI document: 1.0
    Contact: mike.ralphson@gmail.com
    Created by: https://github.com/mermade/mashery2openapi
"""

from rotten_tomatoes_python_sdk.paths.lists_movies_box_office_json.get import GetBoxOfficeJsonRaw
from rotten_tomatoes_python_sdk.paths.lists_movies_in_theaters_json.get import GetIntheaterMoviesRaw
from rotten_tomatoes_python_sdk.paths.lists_movies_opening_json.get import GetOpeningMoviesRaw
from rotten_tomatoes_python_sdk.paths.lists_movies_upcoming_json.get import GetUpcomingMoviesRaw


class MovieListsApiRaw(
    GetBoxOfficeJsonRaw,
    GetIntheaterMoviesRaw,
    GetOpeningMoviesRaw,
    GetUpcomingMoviesRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
