# coding: utf-8

"""
    Rotten Tomatoes

    Test our API services using I/O Docs.

    The version of the OpenAPI document: 1.0
    Contact: mike.ralphson@gmail.com
    Created by: https://github.com/mermade/mashery2openapi
"""

from rotten_tomatoes_python_sdk.paths.lists_movies_box_office_json.get import GetBoxOfficeJson
from rotten_tomatoes_python_sdk.paths.lists_movies_in_theaters_json.get import GetIntheaterMovies
from rotten_tomatoes_python_sdk.paths.lists_movies_opening_json.get import GetOpeningMovies
from rotten_tomatoes_python_sdk.paths.lists_movies_upcoming_json.get import GetUpcomingMovies
from rotten_tomatoes_python_sdk.apis.tags.movie_lists_api_raw import MovieListsApiRaw


class MovieListsApi(
    GetBoxOfficeJson,
    GetIntheaterMovies,
    GetOpeningMovies,
    GetUpcomingMovies,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: MovieListsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = MovieListsApiRaw(api_client)
