# coding: utf-8

"""
    Rotten Tomatoes

    Test our API services using I/O Docs.

    The version of the OpenAPI document: 1.0
    Contact: mike.ralphson@gmail.com
    Created by: https://github.com/mermade/mashery2openapi
"""

from rotten_tomatoes_python_sdk.paths.movies_json.get import MoviesJson
from rotten_tomatoes_python_sdk.apis.tags.search_api_raw import SearchApiRaw


class SearchApi(
    MoviesJson,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: SearchApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = SearchApiRaw(api_client)
