# coding: utf-8

"""
    Rotten Tomatoes

    Test our API services using I/O Docs.

    The version of the OpenAPI document: 1.0
    Contact: mike.ralphson@gmail.com
    Created by: https://github.com/mermade/mashery2openapi
"""

from rotten_tomatoes_python_sdk.paths.lists_json.get import GetDataRaw
from rotten_tomatoes_python_sdk.paths.lists_dvds_json.get import GetDvdsRaw
from rotten_tomatoes_python_sdk.paths.lists_movies_json.get import GetMoviesJsonRaw


class TopLevelListsApiRaw(
    GetDataRaw,
    GetDvdsRaw,
    GetMoviesJsonRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
