# coding: utf-8

"""
    Rotten Tomatoes

    Test our API services using I/O Docs.

    The version of the OpenAPI document: 1.0
    Contact: mike.ralphson@gmail.com
    Created by: https://github.com/mermade/mashery2openapi
"""

from rotten_tomatoes_python_sdk.paths.lists_json.get import GetData
from rotten_tomatoes_python_sdk.paths.lists_dvds_json.get import GetDvds
from rotten_tomatoes_python_sdk.paths.lists_movies_json.get import GetMoviesJson
from rotten_tomatoes_python_sdk.apis.tags.top_level_lists_api_raw import TopLevelListsApiRaw


class TopLevelListsApi(
    GetData,
    GetDvds,
    GetMoviesJson,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TopLevelListsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TopLevelListsApiRaw(api_client)
